[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
  size = 16
  # Line height
  offset = { y = 5 }
  normal = { family = "Monaco Nerd Font Mono", style = "Regular" }
  bold = { family = "Monaco Nerd Font Mono", style = "Bold" }
  italic = { family = "Monaco Nerd Font Mono", style = "Regular Italic" }
  bold_italic = { family = "Monaco Nerd Font Mono", style = "Bold Italic" }

[env]
# Fix color in tmux
TERM = "xterm-256color"

[window]
  startup_mode = "maximized"
  option_as_alt = "Both"

